baseURL = "/"
contentDir = "content/groupdocs-v2"
languageCode = "en-us"
theme = "homepage-v2-theme"
title = "aspose.app"
#disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
# googleAnalytics = ""
#googletagmanager = "GTM-NJMHSH"
contentauthor = "Aspose"
contentsection = "com"
faviconfolder = "aspose"
# googlesiteverification="2vJhDsnM62r8UD51HUo-8kUDylZUY-AmS621DeR8G4k"
baidusiteverification = ""
generator = "Aspose – Free File Format Apps"
metafbtwitter = ""
twitterimage = ""
yandexverification = ""

################################# Menus ##############################
[params.dynamicmenuid]
ar = "groupdocs-ar"
az = "groupdocs-az"
bg = "groupdocs-bg"
bn = "groupdocs-bn"
cs = "groupdocs-cs"
da = "groupdocs-da"
de = "groupdocs-de"
el = "groupdocs-el"
en = "groupdocs-en"
es = "groupdocs-es"
fa = "groupdocs-fa"
fi = "groupdocs-fi"
fr = "groupdocs-fr"
ga = "groupdocs-ga"
he = "groupdocs-iw"
hi = "groupdocs-hi"
hu = "groupdocs-hu"
id = "groupdocs-id"
it = "groupdocs-it"
ja = "groupdocs-ja"
ko = "groupdocs-ko"
lt = "groupdocs-lt"
lv = "groupdocs-lv"
ms = "groupdocs-ms"
nl = "groupdocs-nl"
no = "groupdocs-no"
pl = "groupdocs-pl"
pt = "groupdocs-pt"
ro = "groupdocs-ro"
ru = "groupdocs-ru"
sv = "groupdocs-sv"
th = "groupdocs-th"
tr = "groupdocs-tr"
uk = "groupdocs-uk"
vi = "groupdocs-vi"
zh = "groupdocs-zh"

################################# Localization #########################
# Disabled languages
defaultContentLang = 'en'
disableLanguages = []

[languages]
[languages.en]
contentDir = "content/groupdocs-v2/en"
flag = "flag-us"
languageCode = "en"
languageName = "English"
weight = 1
[languages.fr]
contentDir = "content/groupdocs-v2/fr"
flag = "flag-fr"
languageCode = "fr"
languageName = "Français"
weight = 2
[languages.zh]
contentDir = "content/groupdocs-v2/zh"
flag = "flag-cn"
languageCode = "zh"
languageName = "中文"
weight = 3
[languages.ru]
contentDir = "content/groupdocs-v2/ru"
flag = "flag-ru"
languageCode = "ru"
languageName = "Русский"
weight = 4
[languages.de]
contentDir = "content/groupdocs-v2/de"
flag = "flag-de"
languageCode = "de"
languageName = "Deutsch"
weight = 5
[languages.ja]
contentDir = "content/groupdocs-v2/ja"
flag = "flag-jp"
languageCode = "ja"
languageName = "日本語"
weight = 6
[languages.es]
contentDir = "content/groupdocs-v2/es"
flag = "flag-es"
languageCode = "es"
languageName = "Español"
weight = 7
[languages.ar]
contentDir = "content/groupdocs-v2/ar"
flag = "flag-sa"
languageCode = "ar"
languageName = "عربي"
weight = 8
[languages.da]
contentDir = "content/groupdocs-v2/da"
flag = "flag-da"
languageCode = "da"
languageName = "Dansk"
weight = 9
[languages.el]
contentDir = "content/groupdocs-v2/el"
flag = "flag-gr"
languageCode = "el"
languageName = "Ελληνικά"
weight = 10
[languages.it]
contentDir = "content/groupdocs-v2/it"
flag = "flag-it"
languageCode = "it"
languageName = "Italiano"
weight = 11
[languages.pt]
contentDir = "content/groupdocs-v2/pt"
flag = "flag-pt"
languageCode = "pt"
languageName = "Português"
weight = 12
[languages.sv]
contentDir = "content/groupdocs-v2/sv"
flag = "flag-sv"
languageCode = "sv"
languageName = "Svenska"
weight = 13
[languages.tr]
contentDir = "content/groupdocs-v2/tr"
flag = "flag-tr"
languageCode = "tr"
languageName = "Türkçe"
weight = 14
[languages.az]
contentDir = "content/groupdocs-v2/az"
flag = "flag-az"
languageCode = "az"
languageName = "Azeri"
weight = 15

[languages.bg]
contentDir = "content/groupdocs-v2/bg"
flag = "flag-bg"
languageCode = "bg"
languageName = "Bulgarian"
weight = 16
[languages.bn]
contentDir = "content/groupdocs-v2/bn"
flag = "flag-bn"
languageCode = "bn"
languageName = "Bengali"
weight = 17
[languages.fa]
contentDir = "content/groupdocs-v2/fa"
flag = "flag-fa"
languageCode = "fa"
languageName = "Persian"
weight = 18
[languages.cs]
contentDir = "content/groupdocs-v2/cs"
flag = "flag-cs"
languageCode = "cs"
languageName = "Czech"
weight = 19
[languages.fi]
contentDir = "content/groupdocs-v2/fi"
flag = "flag-fi"
languageCode = "fi"
languageName = "Finnish"
weight = 20
[languages.ga]
contentDir = "content/groupdocs-v2/ga"
flag = "flag-ga"
languageCode = "ga"
languageName = "Gaeilge"
weight = 21
[languages.he]
contentDir = "content/groupdocs-v2/he"
flag = "flag-he"
languageCode = "he"
languageName = "Hebrew"
weight = 22
[languages.hi]
contentDir = "content/groupdocs-v2/hi"
flag = "flag-hi"
languageCode = "hi"
languageName = "Hindi"
weight = 23
[languages.hu]
contentDir = "content/groupdocs-v2/hu"
flag = "flag-hu"
languageCode = "hu"
languageName = "Hungarian"
weight = 24
[languages.id]
contentDir = "content/groupdocs-v2/id"
flag = "flag-id"
languageCode = "id"
languageName = "Indonesia"
weight = 25
[languages.lv]
contentDir = "content/groupdocs-v2/lv"
flag = "flag-lv"
languageCode = "lv"
languageName = "Latvian"
weight = 26
[languages.ms]
contentDir = "content/groupdocs-v2/ms"
flag = "flag-ms"
languageCode = "ms"
languageName = "Malay"
weight = 27
[languages.nl]
contentDir = "content/groupdocs-v2/nl"
flag = "flag-nl"
languageCode = "nl"
languageName = "Nederlands"
weight = 28
[languages.no]
contentDir = "content/groupdocs-v2/no"
flag = "flag-no"
languageCode = "no"
languageName = "Norsk"
weight = 29
[languages.pl]
contentDir = "content/groupdocs-v2/pl"
flag = "flag-pl"
languageCode = "pl"
languageName = "Polskie"
weight = 30
[languages.ro]
contentDir = "content/groupdocs-v2/ro"
flag = "flag-ro"
languageCode = "ro"
languageName = "Romanian"
weight = 31
[languages.th]
contentDir = "content/groupdocs-v2/th"
flag = "flag-th"
languageCode = "th"
languageName = "Thai"
weight = 32
[languages.uk]
contentDir = "content/groupdocs-v2/uk"
flag = "flag-uk"
languageCode = "uk"
languageName = "Ukrainian"
weight = 33
[languages.vi]
contentDir = "content/groupdocs-v2/vi"
flag = "flag-vi"
languageCode = "vi"
languageName = "Vietnamese"
weight = 34
[languages.ko]
contentDir = "content/groupdocs-v2/ko"
flag = "flag-ko"
languageCode = "ko"
languageName = "Korean"
weight = 35
[languages.lt]
contentDir = "content/groupdocs-v2/lt"
flag = "flag-lt"
languageCode = "lt"
languageName = "Lithuanian"
weight = 36

# Title of 404 page
title_404_page = "404 - Page Not Found | metrics.aspose.com"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

#[deployment]

#[[deployment.targets]]
#name = "Stage"
#URL = "s3://qa.aspose.com/?region=us-west-2"

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
contentType = "application/xml"
force = true
gzip = true
pattern = "^.+\\.(xml)$"

[taxonomies]
'downloads/package-manager' = 'downloads/package-managers'
'downloads/product-family' = 'downloads/product-families'
'downloads/programming-language' = 'downloads/programming-languages'

[caches]
[caches.getjson]
dir = ':cacheDir/:project'
maxAge = '1m'
